build:
  ci:
    - echo "true"

jobs:
  - name: sample_node_runCI
    type: runCI
    depdendencyMode: strict
    priority: 10
    steps:
      - OUT: hiptest-img
      
  - name: sample_c_runCI
    type: runCI
    depdendencyMode: strict
    steps:
      - IN: sample_node_runCI
      
  - name: sample_java_runCI
    type: runCI
    depdendencyMode: strict
    priority: 9990
    steps:
      - IN: sample_c_runCI

  - name: runSh1
    type: runSh
    dependencyMode: strict
    priority: 11
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: runSh2
    type: runSh
    dependencyMode: strict    
    steps:
      - IN: runSh1
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:     
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: runSh3
    type: runSh
    dependencyMode: strict
    priority: 9991    
    steps:
      - IN: runSh3
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:     
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: stall
    type: runSh   
    steps:
      - TASK:     
        - script: secs=300; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done             

resources:
  - name: hiptest-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: HiptestDockerHub
    type: integration
    integration: "docker-subint"
        
  - name: hiptest-pipelines-repo
    type: gitRepo
    integration: "github-subint"
    pointer:
      sourceName: ankul-shippable/pipelines
      branch: master
