build:
  ci:
    - echo "true"

jobs:
  - name: 1a_runCI
    type: runCI
    steps:       
      - OUT: 2a_img
      - OUT: 2b_img

  - name: 1b_runSh
    type: runSh
    steps:  
      - TASK:
        - script: secs=30; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        - script: if [ "$(($BUILD_NUMBER % 2))" -eq 0 ]; then export IMAGE_NAME=2c_img; else export IMAGE_NAME=2d_img; fi
        - script: echo "IMAGE_NAME="$IMAGE_NAME 
        - script: shipctl post_resource_state $IMAGE_NAME versionName "build_"$BUILD_NUMBER       
      - OUT: 2c_img
      - OUT: 2d_img

  - name: 1d_runSh
    type: runSh
    steps:  
      - TASK:
        - script: secs=30; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name:3a_runCI
    type: runCI
    steps:
      - IN: 2a_img
      - IN: 2b_img
      - IN: 2c_img
      - IN: 2d_img
      - IN: 1c_runCI
      - IN: 1d_runSh
      - OUT: 4a_img
      - OUT: 4b_img

  - name: 3b_runSh
    type: runSh
    steps:
      - IN: 2a_img
      - IN: 2b_img
      - IN: 2c_img
      - IN: 2d_img
      - IN: 1c_runCI
      - IN: 1d_runSh    
      - TASK:
        - script: secs=30; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        - script: if [ "$(($BUILD_NUMBER % 2))" -eq 0 ]; then export IMAGE_NAME=4a_img; else export IMAGE_NAME=4b_img; fi
        - script: echo "IMAGE_NAME="$IMAGE_NAME 
        - script: shipctl post_resource_state $IMAGE_NAME versionName "build_"$BUILD_NUMBER       
      - OUT: 4a_img
      - OUT: 4b_img


  - name: 5a_runSh
    type: runSh
    steps:
      - IN: 4a_img
      - IN: 4b_img

resources:
  - name: 2a_img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
    
  - name: 2b_img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10 

  - name: 2c_img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
    
  - name: 2d_img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10 

  - name: 4a_img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
    
  - name: 4b_img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10 
