jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-image

  - name: DDC-deploy
    type: deploy
    method: blueGreen
    stabilityDuration: 60 # (seconds)
    maxWaitTime: 1 # (seconds)    
    steps:
      - IN: manifest-job
      - IN: DDC-cluster
      - IN: scaler

resources:
  - name: scaler
    type: replicas
    version:
      count: 1

  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: ECS-cluster
    type: cluster
    integration: "ecs-subint"
    versionTemplate:
      sourceName: "gke-cluster"
      region: "us-central1-a"
      bastionHost:
        address: 35.226.229.205
        user: ankul
        keyIntegration: "bastion-access"      
      
  - name: bastion-access
    type: integration
    integration: "bastion-access-keys"
