build:
  ci:
    - echo "true"

jobs:
  - name: sample_node_runCI
    type: runCI
    steps:
      - OUT: hiptest-img

  - name: ember-tests-job
    type: runSh
    dependencyMode: strict
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: rspec-tests-job
    type: runSh
    dependencyMode: strict    
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:     
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: feature-tests-job
    type: runSh
    dependencyMode: strict    
    steps:
      - IN: ember-tests-job
      - IN: rspec-tests-job
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:     
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done     
        
  - name: final-tests-job
    type: runSh
    dependencyMode: strict    
    steps:
      - IN: feature-tests-job    
      - TASK:     
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done             

resources:
  - name: hiptest-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: HiptestDockerHub
    type: integration
    integration: "docker-subint"
        
  - name: hiptest-pipelines-repo
    type: gitRepo
    integration: "github-subint"
    pointer:
      sourceName: ankul-shippable/pipelines
      branch: master
