jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-image

  - name: ECS-deploy
    type: deploy
    method: upgrade  
    steps:
      - IN: manifest-job
      - IN: ECS-cluster
      - IN: scaler
      - IN: dockerOptions
      - IN: classicLB
        applyTo:
          - manifest: manifest-job
            image: nginx-image
            port: 80

resources:
  - name: scaler
    type: replicas
    version:
      count: 2

  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/app2"
    seed:
      versionName: latest

  - name: ECS-cluster
    type: cluster
    integration: "ecs-subint"
    versionTemplate:
      sourceName: "ecs-cluster"
      region: "us-west-2"
    
  - name: classicLB
    type: loadBalancer
    versionTemplate:
      sourceName: classiclb
      method: classic
      role: "lb_role"
      
  - name: dockerOptions
    type: dockerOptions
    versionTemplate:
      portMappings:
        - "80:80/tcp" #hostPort:containerPort/protocol (udp|tcp)      
