build:
  ci:
    - echo "true"

jobs:      
  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: sample_c_runCI
        triggerOnFailure: false
        triggerOnSuccess: false
      - IN: sample_node_runCI
        triggerOnFailure: true
        triggerOnSuccess: true
      - IN: externalCI-1a
 
  - name: runSh1
    type: runSh
    steps:
      - TASK:
        - script: failing_it
  
  - name: runSh2
    type: runSh
    steps:  
      - TASK:     
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: runSh3
    type: runSh
    steps:
      - IN: runSh2
        triggerOnFailure: false
        triggerOnSuccess: false
      - IN: runSh1
        triggerOnFailure: true
        triggerOnSuccess: true
      - TASK:     
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
                    

resources:
  - name: hiptest-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
