build:
  ci:
    - echo "true"

jobs:
  - name: sample_node_runCI
    type: runCI
    steps:
      - OUT: hiptest-img

  - name: ember-tests-job
    type: runSh   
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: secs=20; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
    on_success:
      - NOTIFY: notify-hiptest-dev-team 

  - name: rspec-tests-job
    type: runSh   
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
    on_success:
      - NOTIFY: notify-hiptest-dev-team    


  - name: feature-tests-job
    type: runSh
    dependencyMode: strict
    steps:
      - IN: ember-tests-job
      - IN: rspec-tests-job
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
    on_success:
      - NOTIFY: notify-hiptest-dev-team          



resources:
  - name: hiptest-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: HiptestDockerHub
    type: integration
    integration: "docker-subint"

  - name: notify-hiptest-dev-team
    type: notification
    integration: "slack-subint"
    pointer:
      recipients:
        - "#test-5148"
        
  - name: hiptest-pipelines-repo
    type: gitRepo
    integration: "github-subint"
    pointer:
      sourceName: ankul-shippable/pipelines
      branch: master

  - name: hiptest-final-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.11

  - name: hiptest-frontend-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.12
      
  - name: hiptest-backend-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.9
      
  - name: hiptest-repo
    type: gitRepo
    integration: "github-subint"
    pointer:
      sourceName: ankul-shippable/hiptest
      branch: master

  - name: Github
    type: integration
    integration: "github-subint"
