build:
  ci:
    - echo "true2"

jobs:
  - name: manifest-1
    type: manifest
    steps:
      - IN: nginx-image
      
  - name: manifest-2
    type: manifest
    steps:
      - IN: nginx-image

  - name: no_notification
    type: runSh
    steps:
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
    on_success:
      script:
        - echo "done"  

  - name: old_syntax
    type: runSh
    steps:
      - IN: manifest-1
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
    on_success:
      - NOTIFY: email_notify
        sendFailingSnippet: true
      - NOTIFY: email_notify
        someotherflag: true        
      - NOTIFY: slack_notify
      - script: echo "old_syntax on_success"
    on_failure:
      - NOTIFY: email_notify
        sendFailingSnippet: true
      - NOTIFY: email_notify
        someotherflag: true        
      - NOTIFY: slack_notify
      - script: echo "old_syntax on_failure"
    on_cancel:
      - NOTIFY: email_notify
        sendFailingSnippet: true
      - NOTIFY: email_notify
        someotherflag: true        
      - NOTIFY: slack_notify
      - script: echo "old_syntax on_cancel"
    on_start:
      - NOTIFY: email_notify
        sendFailingSnippet: true
      - NOTIFY: email_notify
        someotherflag: true        
      - NOTIFY: slack_notify
      - script: echo "old_syntax on_start"
    always:
      - NOTIFY: email_notify
        sendFailingSnippet: true
      - NOTIFY: email_notify
        someotherflag: true        
      - NOTIFY: slack_notify
      - script: echo "old_syntax always"      
      

  - name: new_syntax
    type: runSh
    steps:
      - IN: manifest-2    
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
    on_success:
      script:
        - echo "new_syntax on_success"
      NOTIFY:
        - name: email_notify
          sendFailingSnippet: true
        - name: email_notify
          someotherflag: false            
        - name: slack_notify       
    on_failure:
      script:
        - echo "new_syntax on_failure"
      NOTIFY:
        - name: email_notify
          sendFailingSnippet: true
        - name: email_notify
          someotherflag: false            
        - name: slack_notify       
    on_cancel:
      script:
        - echo "new_syntax on_cancel"
      NOTIFY:
        - name: email_notify
          sendFailingSnippet: true
        - name: email_notify
          someotherflag: false            
        - name: slack_notify       
      on_start:
      script:
        - echo "new_syntax on_start"
      NOTIFY:
        - name: email_notify
          sendFailingSnippet: true
        - name: email_notify
          someotherflag: false            
        - name: slack_notify       
     always:
      script:
        - echo "new_syntax always"
      NOTIFY:
        - name: email_notify
          sendFailingSnippet: true
        - name: email_notify
          someotherflag: false            
        - name: slack_notify              
                

resources:
  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
      
  - name: email_notify
    type: notification
    versionTemplate:
      method: email
      recipients:
        - "ankul@shippable.com"
        
  - name: slack_notify
    type: notification
    integration: "slack-subint"
    versionTemplate:
      recipients:
        - "#test-5148"     
