build:
  ci:
    - echo "true"

jobs:
  - name: test_external
    type: runSh
    runtime:
      timeoutMinutes: 25    
    steps:
      - IN: externalCI-1
      - TASK:
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: externalCI-1b
    type: externalCI   
    steps:
      - IN: image_test_nginx

resources:
  - name: external_ci_test
    type: externalCIServer

  - name: image_test_nginx
    type: image
    integration: "github-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
