build:
  ci:
    - echo "true"

jobs:
  - name: sample_node_runCI
    type: runCI
    steps:
      - OUT: hiptest-img

  - name: ember-tests-job
    type: runSh
    runtime:
      timeoutMinutes: 25    
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: apt-get update && apt-get install python
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: rspec-tests-job
    type: runSh   
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: apt-get update && apt-get install python      
        - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 


  - name: feature-tests-job
    type: runSh
    dependencyMode: strict   
    steps:
      - IN: ember-tests-job
      - IN: rspec-tests-job
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: apt-get update && apt-get install python      
        - script: secs=1000; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        
  - name: test_1
    type: runSh
    runtime:
      timeoutMinutes: -10
    steps:    
      - TASK:
        - script: secs=120; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done        

  - name: test_2
    type: runSh
    runtime:
      timeoutMinutes: 45
    steps:    
      - TASK:
        - script: secs=120; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: test_3
    type: runSh
    runtime:
      timeoutMinutes: 450
    steps:    
      - TASK:
        - script: secs=120; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         

  #- name: h4h-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-final-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team  
      
  #- name: sync-e2e-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-frontend-img
  #    - IN: hiptest-backend-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: if [ \"$HIPTESTFRONTENDIMG_VERSIONNAME\" != \"$HIPTESTBACKENDIMG_VERSIONNAME\" ]; then exit 1; fi
  #    - OUT: hiptest-final-img
  #      replicate: hiptest-backend-img

  #- name: postgres-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team  
      
  #- name: reboot-tests-job
  #  type: runSh
  #  runtime:
  #   container: false
  #  steps:
  #    - IN: hiptest-final-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team        

  #- name: teaspoon-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team 
      
  #- name: execute-rspec-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team 
      
  #- name: execute-postgres-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team 
      
  #- name: execute-ember-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team 
      
  #- name: execute-reboot-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team 
      
  #- name: execute-teaspoon-tests-job
  #  type: runSh
  #  steps:
  #    - IN: hiptest-img
  #    - IN: hiptest-pipelines-repo
  #      switch: off      
  #    - IN: HiptestDockerHub
  #      switch: off      
  #    - TASK:
  #      - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
  #  on_success:
  #    - NOTIFY: notify-hiptest-dev-team       

resources:
  - name: hiptest-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: HiptestDockerHub
    type: integration
    integration: "docker-subint"

  #- name: notify-hiptest-dev-team
  #  type: notification
  #  integration: "slack-subint"
  #  pointer:
  #    recipients:
  #      - "#test-5148"
        
  - name: hiptest-pipelines-repo
    type: gitRepo
    integration: "github-subint"
    pointer:
      sourceName: ankul-shippable/pipelines
      branch: master

  #- name: hiptest-final-img
    #type: image
    #integration: "docker-subint"
    #pointer:
      #sourceName: "ankul/nginx"
    #seed:
      #versionName: prod.11

  #- name: hiptest-frontend-img
    #type: image
    #integration: "docker-subint"
    #pointer:
      #sourceName: "ankul/nginx"
    #seed:
      #versionName: prod.12
      
  #- name: hiptest-backend-img
  #  type: image
  #  integration: "docker-subint"
  #  pointer:
  #    sourceName: "ankul/nginx"
  #  seed:
  #    versionName: prod.9
      
  #- name: hiptest-repo
  #  type: gitRepo
  #  integration: "github-subint"
  #  pointer:
  #    sourceName: ankul-shippable/hiptest
  #    branch: master

  #- name: Github
  #  type: integration
  #  integration: "github-subint"
