build:
  ci:
    - echo "true"

jobs:
  - name: runSh
    type: runSh
    steps:
      - IN: sample_node_runCI
        triggerOnFailure: true
      - IN: sample_java_runCI
        triggerOnFailure: false
      - IN: sample_c_runCI
        triggerOnSuccess: false
      - IN: sample_python_runCI
        triggerOnFailure: false  
        triggerOnSuccess: false
      - IN: sample_scala_runCI
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
