build:
  ci:
    - echo "true"

jobs:
  - name: job-0b
    type: runSh
    steps:
      - TASK:
          - script: echo true   

  - name: job-0a
    type: runSh
    steps:
      - IN: state-1
      - IN: job-0b
      - TASK:
          - script: echo true          

  - name: job-1a
    type: runSh
    steps:
      - IN: job-0a
      - TASK:
          - script: echo true
          
  - name: job-1b
    type: runSh
    steps:
      - IN: job-0a
      - TASK:
          - script: echo true          
      
  - name: job-2
    type: runSh
    steps:
      - IN: state-1
      - IN: job-1a
      - IN: job-1b
      - TASK:
        - script: shipctl get_resource_version_key state-1 "BUILD"
        - script: shipctl post_resource_state state-1 "BUILD" "build_"$BUILD_NUMBER
      - OUT: state-1      


resources:
  - name: state-1
    type: state
