build:
  ci:
    - echo "true"

jobs:
  - name: job-1
    type: runSh
    steps:
#       - IN: state-1
      - TASK:
        - script: shipctl get_resource_version_key state-1 "BUILD"
        - script: shipctl post_resource_state state-1 "BUILD" "build_"$BUILD_NUMBER
#       - OUT: state-1
      
  - name: job-2
    type: runSh
    steps:
      - IN: state-1
      - IN: job-1
      - TASK:
        - script: shipctl get_resource_version_key state-1 "BUILD"
        - script: shipctl post_resource_state state-1 "BUILD" "build_"$BUILD_NUMBER
      - OUT: state-1      


resources:
  - name: state-1
    type: state
