build:
  ci:
    - echo "true"

jobs:
  - name: trigger
    type: runSh
    steps:  
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: job-A
    type: runSh
    steps:  
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        - script: shipctl post_resource_state img-1 versionName "build_"$BUILD_NUMBER       
      - OUT: img-1

  - name: job-B
    type: runSh
    dependencyMode: strict
    steps:
      - IN: img-1
      - IN: img-2
      - IN: trigger
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: job-C
    type: runSh
    dependencyMode: strict
    steps:
      - IN: job-A
      - IN: img-3
      - IN: trigger
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         


resources:
  - name: img-1
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
    
  - name: img-2
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.11
      
  - name: img-3
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.9   
