build:
  ci:
    - echo "true"

jobs:
  - name: sample_node_runCI
    type: runCI
    priority: 10000
    steps:
      - OUT: hiptest-img

  - name: ember-tests-job
    type: runSh
    priority: 10000
    runtime:
      timeoutMinutes: 25    
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: apt-get update && apt-get install python
        - script: secs=6; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: rspec-tests-job
    type: runSh   
    steps:
      - IN: hiptest-img
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: apt-get update && apt-get install python      
        - script: secs=5; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 


  - name: feature-tests-job
    type: runSh
    dependencyMode: strict   
    steps:
      - IN: ember-tests-job
      - IN: rspec-tests-job
      - IN: hiptest-pipelines-repo
        switch: off      
      - IN: HiptestDockerHub
        switch: off      
      - TASK:
        - script: apt-get update && apt-get install python      
        - script: secs=1000; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done     

resources:
  - name: hiptest-img
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: HiptestDockerHub
    type: integration
    integration: "docker-subint"
        
  - name: hiptest-pipelines-repo
    type: gitRepo
    integration: "github-subint"
    pointer:
      sourceName: ankul-shippable/pipelines
      branch: master
