build:
  ci:
    - echo "true"

jobs:
  - name: runSh
    type: runSh
    steps:
      - IN: sample_node_runCI
        triggerOnFailure: true
      - IN: sample_java_runCI
        triggerOnFailure: false
      - IN: sample_c_runCI
        triggerOnSuccess: false
      - IN: sample_python_runCI
        triggerOnFailure: false  
        triggerOnSuccess: false
      - IN: sample_scala_runCI
      - IN: runSh-1
        triggerOnFailure: true
      - IN: runSh-2
        triggerOnFailure: true
      - IN: runSh-3
        triggerOnFailure: false
      - IN: image
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: runSh-1
    type: runSh
    steps:
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
 
  - name: runSh-2
    type: runSh
    steps:
      - TASK:
        - script: failing it
        
  - name: runSh-3
    type: runSh
    steps:
      - TASK:
        - script: if [ "$(($BUILD_NUMBER % 2))" -eq 0 ]; then failing it; fi # fail if build number is even     
        

resources:
  - name: image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10        
