jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-image

  - name: KUBE-deploy
    type: deploy
    method: blueGreen
    steps:
      - IN: manifest-job
      - IN: KUBE-cluster
      - IN: kube-access

resources:
  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10

  - name: kube-access
    type: integration
    integration: "ssh-subint"

  - name: KUBE-cluster
    type: cluster
    integration: "kube-subint"
    pointer:
      bastionHost:
        address: 34.221.17.67
        user: ubuntu
        keyIntegration: "kube-access"
