jobs:
  - name: job-foo
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done   

resources:
  - name: resource-foo
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
